### ISSUE TITLE
Default type conversions

### ISSUE THREAD

**Issue by konstantin-ogulchansky** [candy-kingdom/cli#26]
_As a CLI developer, I want to be able to define types of arguments._

## API
```python
# yell.py

from candies import cli
from candies.cli import Opt

@cli
def main(phrase: Arg[str]('Phrase to yell.'),
         times:  Opt[int]('How many times to yell.')):
    for _ in range(times):
        print(phrase)

if __name__ == '__main__':
    main()
```
Whenever this CLI is invoked, the argument `phrase` is converted to `str` (i.e., passed as is), and `times` is converted to `int` (if such conversion is possible; otherwise, an explanatory error message is shown).

## Requirements
* Code should be tested.

**Comment by konstantin-ogulchansky** [comment]
We should probably think of providing an ability for users to define their own conversion rules for custom types.

**Comment by JoshuaLight** [comment]
How about such syntax?
```py
# money.py

from candies.cli import cli, parse, Opt

from core import Money

# Our package only knows about basic parsing techniques,
# so the custom one can be defined.
@parse
def to_money(str) -> Money:
    if str is None or str == '':
        return None

    if str[0] == '$':
        return Money.dollars(float(str[1:]))

    # etc.

@cli
def add(price: Arg[Money]('How much to add to the bank account.')):
    ...
```

But I'm wondering whether it's ok to define custom parsers as separate functions or it'd be better to expect `parse` or `parse_from` static method right in the `Money` type?

```py
# money.py

from candies.cli import cli, parse, Opt

class Money:
    @staticmethod
    def parse(x: str) -> 'Money':
        ...

@cli
def add(price: Arg[Money]('How much to add to the bank account.')):
    ...
```

What do you think?
