### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by JoshuaLight** [candy-kingdom/cli#3]
_As a CLI developer, I want to be able to define a function with named arguments that will act as a CLI root._

## API
```python
# copy.py

from candies import cli
from candies.cli import Arg

@cli
def main(source: Arg, destination: Arg): ...

if __name__ == '__main__':
    cli()
```
So this can be called as:
```shell
$ python copy.py ~/1.txt ~/2.txt
```
Or in more verbose way:
```shell
$ python copy.py --source ~/1.txt --destination ~/2.txt
```

## Requirements
- Code should be tested.

## Questions
- How should we deal with argument names like `a_thing`? Should we be able to pass them like `--a-thing`?

**Comment by konstantin-ogulchansky** [comment]
For clarification: shouldn't there be `main()` instead of `cli()`?
```python
if __name__ == '__main__':
    main()
```

**Comment by JoshuaLight** [comment]
I meant `cli`, but this is an open question. What do you think?

As for me, `cli` looks a bit better, because it represents an invocation of command line interface, which is exactly what we do. But of course we'll need to add some ugly checks to `cli` decorator.
