### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by konstantin-ogulchansky** [candy-kingdom/cli#37]
It would probably be nice to have a folder in the repository containing a handful of examples of CLIs of different complexity. For example,

1. A simple CLI with both positional and optional arguments:

    ```python
    # yell.py

    from candies.cli import cli
    from candies.cli.args import Arg, Opt

    @cli
    def yell(phrase: Arg[str]('A phrase to yell.'),
             times:  Opt[int]('How many times to yell.')):
        """Prints a phrase a specified amount of times."""

        for _ in range(times):
            print(phrase)

    if __name__ == '__main__':
        cli()
    ```
    
    This can be used as follows:

    ```bash
    $ python yell.py --help
    $ python yell.py "Nice!" --times 10
    ```

**Comment by JoshuaLight** [comment]
## Idea
A simulation of rolling dices.

## API
```shell
$ python roll.py 1d6
3
$ python roll.py 1d6
2
5
$ python roll.py 1d6 1d3
6
2
```

## Demonstrates
- Variable arguments.
- Custom parsing (need to parse `1d6`, etc.).

**Comment by JoshuaLight** [comment]
## Idea
A weather information utility.

## API
```shell
$ python weather.py Kharkiv --temp
15°C
```

## Demonstrates
- Positional arguments.
- Flags.
