### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JoshuaLight** [candy-kingdom/cli#8]
_As a CLI developer, I want to have an automatic `--help` flag for all my interfaces. That means I need to have an ability to specify a description for any argument._

## API
```python
# copy.py

from candies import cli
from candies.cli import Arg

@cli
def main(source: Arg('Source file or directory'),
         destination: Arg('Destination path of a file or a directory')):
    """Script or command description."""
```

So it's possible to call:
```
$ python copy.py --help
Usage: copy.py --source <source> --destination <destination>

    Script or command description.

Arguments:
    --source         Source file or directory
    --destination    Destination path of a file or a directory.    
```

### Subcommands
The syntax of `--help` flag for subcommands looks like:
```
$ python copy.py --help
$ python copy.py COMMAND --help
$ python copy.py COMMAND1 COMMAND2 --help
```

### Arguments before/after `--help`
If some arguments are specified before or after `--help` flag and they're not command names, the invocation of the flag should be considered as invalid:
```
$ python copy.py --source ~/1.txt --help
Invalid invocation of `copy.py`: expected `copy.py --help` or `copy.py --source ~1/.txt ...`.
```

## Requirements
- Code should be tested.

**Comment by konstantin-ogulchansky** [comment]
I believe it would also be nice to have the ability to override the output for `--help`. What do you think about the following approach?
```python
# The `help` flag determines whether to add an automatic help command.
# It is `True` by default.
@cli(help=False)
def example(a, b):
    ...

@example.help
def help():
    ...
```

**Comment by JoshuaLight** [comment]
That would be great!

May I suggest some minor simplification of the approach above?
For example, one could write:
```python
@cli
def example(a, b): ...

@example.help
def help(): ...

# When `cli` is called, it's known that `help` for `example` was overridden.
```

**Comment by konstantin-ogulchansky** [comment]
Looks great!
